#生产环境的配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-uax3cv8az000yy5o.rwlb.cn-chengdu.rds.aliyuncs.com:3306/xxxxxxxx?serverTimezone=GMT%2B8&useSSL=true
    username: xxxxxxxxx
    password: xxxxxxxxx
#  redis:
#    host: 47.94.128.215
#    port: 8379
  mail:
    # 发送者邮箱
    username: cqucsblogtest@163.com
    #申请到的授权码
    password: xxxxxxxxxx
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 端口号465或587
    port: 465
    protocol: smtps
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
          debug: true
          ssl: true
#logging:
#  level:
#    pers.qianyucc.qblog.dao: trace
#
#minio:
#  server: http://117.50.23.198:8884/
#  access-key: AKIAIOSFODNN7EXAMPLE
#  secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
#  bucket: qblog
#qiniu:
#  server: http://upload-z2.qiniup.com
#  url: http://images.codingli.xyz/
#  access-key: knQrQNZO7UAIGCmDuXpSt_yeeF2WI_OykM6IITNN
#  secret-key: DYr3LHywS5TdxPuxvcuBsW_3JkfOBnvEkau5Ubvn
#  bucket: qimages-api
#
#setting:
#  path: _qblog/qblog.setting
#remote:
#  logUrl: http://localhost:7004/