server:
  port: 8888
#  servlet:
#    context-path: /api/v1

spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
  profiles:
    active: dev
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  application:
#    name: qblog-server
#logging:
#  file:
#    name: log/qblog.log
#    path: log/
